sudo: false
language: python
before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y graphviz enchant
python:
    - '2.7'
install:
    - pip install -r requirements.txt
script:
    - cd docs; make html
