node {
   stage('Preparation') {
      // Get some code from a GitHub repository
      git 'https://github.com/f5devcentral/f5-automation-labs/jenkins.git'
   }
   stage('Testing') {
      //Run the tests
      //sh "python –m /home/snops/f5-automation-labs/jenkins/f5-newman-operation/f5-newman-build-3"
   }
   stage('Build') {
       //Run SNOPS Container Newman Package Virtual and Pool
      sh "f5-newman-wrapper /home/snops/f5-automation-labs/jenkins/f5-newman-operation/f5-newman-build-3"
      //chatops slack message that run has completed
      slackSend(
         channel: '#jenkins_builds',
         color: 'good',
         message: 'f5-newman-node is disabled!',
         teamDomain: 'f5agilitydevops',
         token: 'vLMQmBq2tiyiCcZoNlbmAi0Z'
         )
   }
}
