node {
   stage('Preparation') {
      // Get some code from a GitHub repository
      git 'https://github.com/f5devcentral/f5-automation-labs/f5-newman-build/jenkins.git'
   }
   stage('Testing') {
      //Run the tests
      //sh "python –m /home/snops/f5-automation-labs/jenkins/f5-newman-build/f5-newman-build-1"
      //sh "python –m /home/snops/f5-automation-labs/jenkins/f5-newman-build/f5-newman-build-2"
   }
   stage('Build') {
       //Run SNOPS Container Newman Package Virtual and Pool
      sh "f5-newman-wrapper /home/snops/f5-automation-labs/jenkins/f5-newman-build/f5-newman-build-1"
      //chatops slack message that run has completed
      slackSend(
         channel: '#jenkins_builds',
         color: 'good',
         message: 'Build of Virtual Server and Pool Worked!',
         teamDomain: 'f5agilitydevops',
         token: 'vLMQmBq2tiyiCcZoNlbmAi0Z'
         )
   }
   stage('Approval') {
      //Gate the process and require approval
      input 'Proceed?'
      //chatops slack message that run has completed
      slackSend(
          channel: '#jenkins_builds',
          color: 'good',
          message: 'Someone Approved Virtual and Pool Creation, thats some serious Continuous Delivery!',
          teamDomain: 'f5agilitydevops',
          token: 'vLMQmBq2tiyiCcZoNlbmAi0Z'
          )
   }
   stage('Re-Enable') {
       //Run SNOPS Container Newman Package add Node to Pool
      sh "f5-newman-wrapper /home/snops/f5-automation-labs/jenkins/f5-newman-build/f5-newman-build-2"
      //chatops slack message that run has completed
      slackSend(
         channel: '#jenkins_builds',
         color: 'good',
         message: 'Someone added a node to pool, production is online!',
         teamDomain: 'f5agilitydevops',
         token: 'vLMQmBq2tiyiCcZoNlbmAi0Z'
         )
   }
}
